version: "3.8"

services:
  app:
    image: iloveoov/student-app-docker:${TAG}
    container_name: student-app
    restart: always
    ports:
      - "3030:3030"
    environment:
      - NODE_ENV=production
